### ISSUE TITLE
[Suggestion] Dark Mode support

### ISSUE THREAD

**Issue by Reyuki-san** [httptoolkit/httptoolkit-ui#91] opened 2023-09-11 01:36 UTC
It would be great if there's dark mode theme as option to users :")

**Comment by pimterry** [comment] 2023-09-11 12:07
Duplicate of https://github.com/httptoolkit/httptoolkit/issues/315 - this does already exist, it's a Pro feature.

If you have HTTP Toolkit Pro, you can find it in the Settings, at the bottom under 'Themes'.

**Closed by pimterry** 2023-09-11 12:07 UTC
